In [1]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [2]:
L =  [ 1 ,2 ,3]

L.insert?

Signature: L.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method

In [3]:
L?

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

In [4]:
def elvcarr(a):
    """renvoie le carre d'un nombre"""
    return a**2

In [5]:
elvcarr?

Signature: elvcarr(a)
Docstring: renvoie le carre d'un nombre
File:      c:\users\bassi\appdata\local\temp\ipykernel_22524\2498513259.py
Type:      function

## Acce a la code source avec ??

In [6]:
elvcarr??

Signature: elvcarr(a)
Source:   
def elvcarr(a):
    """renvoie le carre d'un nombre"""
    return a**2
File:      c:\users\bassi\appdata\local\temp\ipykernel_22524\2498513259.py
Type:      function

In [7]:
len??

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [8]:
print(In[13])

IndexError: list index out of range

In [9]:
import math


In [10]:
math.sin(0.5)

0.479425538604203

In [11]:
math.cos(0.5)

0.8775825618903728

In [12]:
print(In[17])

IndexError: list index out of range

In [13]:
Out[18]

KeyError: 18

In [14]:
Out[18]**2 + Out[17]**2

KeyError: 18

In [15]:
# Pour afficher la dernier valeur de sortie 
print(_)

0.8775825618903728


In [16]:
## Pour afficher l'avant  dernier valeur de sortie 
print(__)

0.479425538604203


In [17]:
#Pour afficher tous 
%history

len?
L =  [ 1 ,2 ,3]

L.insert?
L?
def elvcarr(a):
    """renvoie le carre d'un nombre"""
    return a**2
elvcarr?
elvcarr??
len??
print(In[13])
import math
math.sin(0.5)
math.cos(0.5)
print(In[17])
Out[18]
Out[18]**2 + Out[17]**2
# Pour afficher la dernier valeur de sortie 
print(_)
## Pour afficher l'avant  dernier valeur de sortie 
print(__)
#Pour afficher tous 
%history


In [18]:
%history -n 1-4

   1: len?
   2:
L =  [ 1 ,2 ,3]

L.insert?
   3: L?
   4:
def elvcarr(a):
    """renvoie le carre d'un nombre"""
    return a**2


## Erreur et Débogage

In [19]:
def div(a , b):
    return a/b 



In [20]:
print( div(1 , 0) )

ZeroDivisionError: division by zero

In [21]:
%xmode Verbose

Exception reporting mode: Verbose


In [22]:
print( div(1 , 0) )

ZeroDivisionError: division by zero

In [23]:
%debug

> c:\users\bassi\appdata\local\temp\ipykernel_22524\558240720.py(2)div()



# NUMPY

In [24]:
import numpy as np

In [25]:
np.__version__

'1.26.4'

In [26]:
#pour cree un tablea 
tableau = np.array([ 1,2,3,45,6])
tableau

array([ 1,  2,  3, 45,  6])

In [27]:
np.array([3.14 , 1,2])

array([3.14, 1.  , 2.  ])

In [28]:
np.zeros(10 ,dtype=int )

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
# un tableau contenant des memes valeurs
np.full((3,5) , 1.5)

array([[1.5, 1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5, 1.5]])

In [31]:
# tableau avec secance lineaire
np.arange(1, 20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Accee au attirbuets d'un tableau