In [1]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [2]:
L =  [ 1 ,2 ,3]

L.insert?

Signature: L.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method

In [3]:
L?

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

In [4]:
def elvcarr(a):
    """renvoie le carre d'un nombre"""
    return a**2

In [5]:
elvcarr?

Signature: elvcarr(a)
Docstring: renvoie le carre d'un nombre
File:      c:\users\bassi\appdata\local\temp\ipykernel_22524\2498513259.py
Type:      function

## Acce a la code source avec ??

In [6]:
elvcarr??

Signature: elvcarr(a)
Source:   
def elvcarr(a):
    """renvoie le carre d'un nombre"""
    return a**2
File:      c:\users\bassi\appdata\local\temp\ipykernel_22524\2498513259.py
Type:      function

In [7]:
len??

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [8]:
print(In[13])

IndexError: list index out of range

In [9]:
import math


In [10]:
math.sin(0.5)

0.479425538604203

In [11]:
math.cos(0.5)

0.8775825618903728

In [12]:
print(In[17])

IndexError: list index out of range

In [13]:
Out[18]

KeyError: 18

In [14]:
Out[18]**2 + Out[17]**2

KeyError: 18

In [15]:
# Pour afficher la dernier valeur de sortie 
print(_)

0.8775825618903728


In [16]:
## Pour afficher l'avant  dernier valeur de sortie 
print(__)

0.479425538604203


In [17]:
#Pour afficher tous 
%history

len?
L =  [ 1 ,2 ,3]

L.insert?
L?
def elvcarr(a):
    """renvoie le carre d'un nombre"""
    return a**2
elvcarr?
elvcarr??
len??
print(In[13])
import math
math.sin(0.5)
math.cos(0.5)
print(In[17])
Out[18]
Out[18]**2 + Out[17]**2
# Pour afficher la dernier valeur de sortie 
print(_)
## Pour afficher l'avant  dernier valeur de sortie 
print(__)
#Pour afficher tous 
%history


In [18]:
%history -n 1-4

   1: len?
   2:
L =  [ 1 ,2 ,3]

L.insert?
   3: L?
   4:
def elvcarr(a):
    """renvoie le carre d'un nombre"""
    return a**2


## Erreur et Débogage

In [19]:
def div(a , b):
    return a/b 



In [20]:
print( div(1 , 0) )

ZeroDivisionError: division by zero

In [21]:
%xmode Verbose

Exception reporting mode: Verbose


In [22]:
print( div(1 , 0) )

ZeroDivisionError: division by zero

In [23]:
%debug

> c:\users\bassi\appdata\local\temp\ipykernel_22524\558240720.py(2)div()



# NUMPY

In [24]:
import numpy as np

In [25]:
np.__version__

'1.26.4'

In [26]:
#pour cree un tablea 
tableau = np.array([ 1,2,3,45,6])
tableau

array([ 1,  2,  3, 45,  6])

In [27]:
np.array([3.14 , 1,2])

array([3.14, 1.  , 2.  ])

In [28]:
np.zeros(10 ,dtype=int )

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
# un tableau contenant des memes valeurs
np.full((3,5) , 1.5)

array([[1.5, 1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5, 1.5]])

In [31]:
# tableau avec secance lineaire
np.arange(1, 20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Accee au attirbuets d'un tableau

In [36]:
np.random.seed(0) # pour reproduire le meme resultat
x1 = np.random.randint( 10 , size= 3 ) # tabeau avec une dimenssion
x2 = np.random.randint( 10 , size= (3,3) ) # tableau avec deux dimensions
x3 = np.random.randint( 10 , size= ( 3 , 4, 5  ) ) # trois dimensions



In [37]:
print( "x3 ndim" , x3.ndim )
print( "x3 shape" , x3.shape )
print( "x3 size" , x3.size )

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


# index de tableau et acce a un element 

In [38]:
x1

array([5, 0, 3])

In [39]:
x1[0]

5

In [40]:
x1[-1] # afficher le dernier element du  tableau

3

In [41]:
x2

array([[3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [44]:
x2[0,2]

9

In [46]:
x2[2,-2] # acceder a la dernier ligne et avant derniere  colonne

7

# tranchage (Slice)

In [47]:
X =  np.arange(10)

In [48]:
X[:5]

array([0, 1, 2, 3, 4])

In [49]:
X[5:] # 5 dernier ligne 

array([5, 6, 7, 8, 9])

In [50]:
X[::2] # du debut j'asqu'a la fin par pas de deux 

array([0, 2, 4, 6, 8])

In [51]:
X[1::2] # un sur deux par à partie de l'index 2

array([1, 3, 5, 7, 9])

In [53]:
X[::-1] # commencant par l'inverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [54]:
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
X[5::-1]

array([5, 4, 3, 2, 1, 0])

In [56]:
x2

array([[3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [57]:
x2[ :2, :3 ]

array([[3, 7, 9],
       [3, 5, 2]])

In [69]:
x2[:3,::2]

array([[3, 9],
       [3, 2],
       [4, 6]])

In [71]:
x2

array([[3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [70]:
x2[::-1 , ::-1]

array([[6, 7, 4],
       [2, 5, 3],
       [9, 7, 3]])

In [73]:
x2_sub = x2[:2 , :2]
x2_sub

array([[3, 7],
       [3, 5]])

In [77]:
x2_sub[0,0] = 99 # ici si on modifie la valeur de x2_sub , la valeur de x2 sera aussi modifier .

In [76]:

print(x2)
print(x2_sub)

[[99  7  9]
 [ 3  5  2]
 [ 4  7  6]]
[[99  7]
 [ 3  5]]


In [78]:
# le copie nous permet de ne pas impacter la modification 
x2_sub_copy = x2[:2 , :2].copy()


In [80]:
x2_sub_copy[0,0] =11 
print(x2_sub_copy)
print()
print(x2)

[[11  7]
 [ 3  5]]

[[99  7  9]
 [ 3  5  2]
 [ 4  7  6]]


### reshape

In [81]:
grid = np.arange(12).reshape((3,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
x = np.array([1,2,3])
x


array([1, 2, 3])

In [90]:
x.reshape((3,1))
x

array([1, 2, 3])

In [91]:
x.reshape((1,3))
x

array([1, 2, 3])

In [92]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [93]:
x.reshape((3,1))
x

array([1, 2, 3])

In [94]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])